- name: Server-side of SSH call home
  tags: ssh-call-home
  block:
  - name: Add unprivileged user
    user:
      name: "{{ ssh_user }}"
      state: present
  - name: SSH config dir
    file:
      dest: "/home/{{ ssh_user }}/.ssh"
      owner: "{{ ssh_user }}"
      state: directory
  - name: authorized_keys, exclusively managed by Ansible
    copy:
      dest: "/home/{{ ssh_user }}/.ssh/authorized_keys"
      content: "{{ ssh_public_key }}"

