language: python
dist: trusty
sudo: true
python:
- '3.5'
env:
  global:
    - MSGFLO_BROKER=mqtt://localhost
before_install:
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
before_script:
- mosquitto -d
install:
- pip install -r gateway/requirements.txt
- pip install -r firmware/requirements.txt
script:
- pytest -v
