- name: Configure systemd-timesyncd
  tags: ntp-servers
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify: systemd-timesyncd configuration changed
