- name: Dlock gateway
  tags:
    - dlock-gateway
    - app
  block:
  - name: Install packages
    apt:
      name:
        - python3
        - python3-pip
        - virtualenv
        - python-setuptools
        - git
        - certbot
        - ack
      install_recommends: no

  - name: dlock unprivileged user
    user:
      name: dlock
      state: present

  - name: dlock dir
    file:
      path: /opt/dlock
      owner: dlock
      group: dlock
      state: directory

  - name: Check out dlock repository
    git:
      repo: 'https://github.com/jonnor/dlock-oslo'
      dest: /opt/dlock/src
      version: master

  - name: Install package dependencies
    pip:
      chdir: '/opt/dlock/src'
      requirements: './gateway/requirements.txt'
      virtualenv: /opt/dlock/src/venv
      virtualenv_python: 'python3.5'

  - name: Copy dlock-gateway service file
    copy:
      src: etc/systemd/system/dlock-gateway.service
      dest: /etc/systemd/system/dlock-gateway.service
    notify: restart dlock-gateway

  - name: Copy dlock-testdevices service file
    copy:
      src: etc/systemd/system/dlock-testdevices.service
      dest: /etc/systemd/system/dlock-testdevices.service
    notify: restart dlock-testdevices

  - name: dlock config dir
    file:
      path: /etc/dlock
      state: directory

  - name: dlock-gateway settings 
    template:
      src: gateway.env.j2
      dest: /etc/dlock/gateway.env
    notify: restart dlock-gateway

  - name: dlock-testdevices settings 
    copy:
      content: |
        MSGFLO_BROKER=TODO
      dest: /etc/dlock/testdevices.env
    notify: restart dlock-testdevices

  - name: systemd enable dlock-gateway
    systemd:
      name: dlock-gateway
      enabled: yes

  - name: systemd enable dlock-testdevices
    systemd:
      name: dlock-testdevices
      enabled: "{{ dlock_enable_testdevices }}"

- name: Nginx
  tags: nginx
  become: yes
  block:
  - name: Install Nginx
    apt:
      name:
      - nginx
      install_recommends: no

  - name: nginx site
    template:
      src: dlock.trygvis.io
      dest: /etc/nginx/sites-available/dlock.trygvis.io
    notify: reload nginx

  - name: nginx enable site
    file:
      src: ../sites-available/dlock.trygvis.io
      dest: /etc/nginx/sites-enabled/dlock.trygvis.io
      state: link
    notify: reload nginx
