- name: Dlock gateway
  tags: dlock-gateway
  block:
  - name: Install packages
    apt:
      name:
      - python3
      - python3-pip
      - virtualenv
      - python-setuptools
      - git
      install_recommends: no

  - name: dlock unprivileged user
    user:
      name: dlock
      state: present

  - name: dlock dir
    file:
      path: /opt/dlock
      owner: dlock
      group: dlock
      state: directory

  - name: Check out dlock repository
    git:
      repo: 'https://github.com/jonnor/dlock-oslo'
      dest: /opt/dlock/src
      version: master
  - name: Install package dependencies
    pip:
      chdir: '/opt/dlock/src'
      requirements: './gateway/requirements.txt'
      virtualenv: /opt/dlock/src/venv
      virtualenv_python: 'python3.5'

  - name: Copy dlock-gateway service file
    copy:
      src: etc/systemd/system/dlock-gateway.service
      dest: /etc/systemd/system/dlock-gateway.service

  - name: Copy dlock-testdevices service file
    copy:
      src: etc/systemd/system/dlock-testdevices.service
      dest: /etc/systemd/system/dlock-testdevices.service

  - name: dlock config dir
    file:
      path: /etc/dlock
      state: directory

  - name: dlock-gateway settings 
    copy:
      content: |
        LOGLEVEL=debug
        DLOCK_IGNORE_MISSING=notresponding-1,dev-0
        DLOCK_API_CREDENTIALS=TODO
        MSGFLO_BROKER=TODO
      dest: /etc/dlock/gateway.env

  - name: dlock-testdevices settings 
    copy:
      content: |
        MSGFLO_BROKER=TODO
      dest: /etc/dlock/testdevices.env

  - name: Start dlock-gateway
    systemd:
      name: dlock-gateway
      state: restarted # TODO, only restart when needed
      enabled: yes
      daemon_reload: yes # TODO, only restart on need

  - name: Start dlock-testdevices
    systemd:
      name: dlock-testdevices
      state: restarted # TODO, only restart when needed
      enabled: yes
      daemon_reload: yes # TODO, only restart on need

- name: Nginx
  tags: nginx
  become: yes
  block:
  - name: Secrets
    include_vars:
      file: 'vault.yml'
    no_log: no
  - name: Install Nginx
    apt:
      name:
      - nginx
      install_recommends: no

  - name: nginx site
    template:
      src: dlock.trygvis.io
      dest: /etc/nginx/sites-available/dlock.trygvis.io

# FIXME: validate command complains about server directive not valid here
#      validate: 'nginx -t -c %s'

  - name: nginx enable site
    file:
      src: ../sites-available/dlock.trygvis.io
      dest: /etc/nginx/sites-enabled/dlock.trygvis.io
      state: link

  - name: Reload nginx
    systemd:
      name: nginx
      state: reloaded
      enabled: yes

- name: Letsencrypt
  tags: letsencrypt
  become: yes
  block:
  # TODO: generate certificates with letsencrypt. https://docs.ansible.com/ansible/latest/modules/letsencrypt_module.html
  - name: Chmod certificates
    file:
      path: "/etc/letsencrypt/{{ item }}"
      owner: mosquitto
      group: root
    with_items:
      - live/dlock.trygvis.io
      - archive/dlock.trygvis.io
  - name: Chmod certificates
    file:
      path: "/etc/letsencrypt/{{ item }}"
      mode: 0770
    with_items:
      - live
      - archive
