- apt:
    name: "{{ items }}"
    install_recommends: no
  vars:
    items:
      - haproxy
      - vim-haproxy

# global
# 	log /dev/log	local0
# 	log /dev/log	local1 notice
# 	chroot /var/lib/haproxy
# 	stats socket /run/haproxy/admin.sock mode 660 level admin
# 	stats timeout 30s
# 	user haproxy
# 	group haproxy
# 	daemon
# 
# 	# Default SSL material locations
# 	ca-base /etc/ssl/certs
# 	crt-base /etc/ssl/private
# 
# 	# Default ciphers to use on SSL-enabled listening sockets.
# 	# For more information, see ciphers(1SSL). This list is from:
# 	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
# 	# An alternative list with additional directives can be obtained from
# 	#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
# 	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
# 	ssl-default-bind-options no-sslv3
# 
# defaults
# 	log	global
# 	mode	http
# 	option	httplog
# 	option	dontlognull
#         timeout connect 5000
#         timeout client  50000
#         timeout server  50000
# 	errorfile 400 /etc/haproxy/errors/400.http
# 	errorfile 403 /etc/haproxy/errors/403.http
# 	errorfile 408 /etc/haproxy/errors/408.http
# 	errorfile 500 /etc/haproxy/errors/500.http
# 	errorfile 502 /etc/haproxy/errors/502.http
# 	errorfile 503 /etc/haproxy/errors/503.http
# 	errorfile 504 /etc/haproxy/errors/504.http


- vars:
    frontends:
      - name: http
        port: 80
      - name: https
        port: 443
      - name: mqtt
        port: 1883
      - name: mqtts
        port: 8883
    backends:
      - name: dlock-prod
        ip: 51.15.70.79
  copy:
    dest: /etc/haproxy/haproxy.cfg
    content: |
      global
        log /dev/log local0
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

      defaults
        log global
        mode tcp
        option tcplog
        # option dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

      listen stats
        bind *:8888
        mode http
        stats enable
        stats uri /
        stats auth admin:admin

      # option clitcpka: Use this to avoid the connection loss when client subscribed for a topic and its idle for sometime
      # timeout client 3h: By default TCP keep-alive interval is 2hours in OS kernal, 'cat /proc/sys/net/ipv4/tcp_keepalive_time'
      # timeout server 3h: By default TCP keep-alive interval is 2hours in OS kernal
      {% for f in frontends %}

      listen {{ f.name }}
        bind *:{{ f.port }}
        mode tcp
        option clitcpka
        timeout client 3h
        timeout server 3h
        option tcplog
        balance leastconn
      {% for s in backends %}
        server {{ s.name }} {{ s.ip }}:{{ f.port }} check
      {% endfor %}
      {% endfor %}
  notify: restart haproxy

- systemd:
    unit: haproxy
    enabled: yes
