- name: /etc/localtime
  file:
    src: /usr/share/zoneinfo/Europe/Oslo
    dest: /etc/localtime
    state: link
    force: yes
  notify: reconfigure tzdata

- name: rm /etc/motd
  file:
    path: /etc/motd
    state: absent

- name: Install packages
  apt:
    name: "{{ dlock_base__packages }}"
    install_recommends: no

- lineinfile:
    path: /etc/hosts
    regexp: '.*\.trygvis.\io'
    line: '127.0.0.1 {{ web_hostname }}'
