- name: restart mosquitto
  service:
    name: mosquitto
    state: restarted
    daemon_reload: yes
  become: yes

- name: systemd daemon-reload
  service:
    daemon_reload: yes

- name: reload mosquitto
  service:
    name: mosquitto
    state: reloaded
  become: yes
