- hosts: 
    - gateways
  roles:
    - network
    - role: dlock-base
      tags: dlock-base
      become: yes
    - lusers
    - superusers
    - role: dlock-gateway
      tags: dlock-gateway
    - role: dlock-testdevices
      tags: dlock-testdevices
    - role: ssh-call-home-server
      tags: ssh-call-home-server
    - role: mqtt-server
      tags: mqtt-server
