- hosts: 
    - gateways
  roles:
    - network
    - role: dlock-base
      tags: dlock-base
      become: yes
    - lusers
    - superusers
    - role: dlock-gateway
      tags: dlock-gateway
    - ssh-call-home-server
    - role: mqtt-server
      tags: mqtt-server

#- hosts:
#    - dlock-proxy
#  roles:
#    - lusers
#    - superusers
#    - role: dlock-base
#      tags: dlock-base
#      become: yes
#    - role: dlock-proxy
#      tags: dlock-proxy
#      become: yes
